# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#  Jacob Chaffin <jchaffin@ucla.edu>
#

#
# Zsh
#
export ZPREZTODIR=$HOME/dotfiles/zsh/prezto

#
# TMPDIR
#
export TMPDIR="/tmp"

# Eclipse
#
export ECLIPSE_HOME=/Applications/Eclipse.app/Contents/Eclipse/

# Perl 5
export PERL5LIB="/usr/local/lib/perl5/site_perl":$PERL5LIB

#
# Node.js
#
# Disable warnings
# https://github.com/nodejs/node/pull/10918
export NODE_NO_WARNINGS='1'

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR=subl
export VISUAL='subl'
export PAGER='less'

# See spacemacs gtags layer
# https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btags/gtags
export GTAGSLABEL=pygments

#
# GPG
#
export GPG_TTY=$(tty)


#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

if (( $#commands[go] )); then
  GOPATH="$HOME/go"
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
  $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
  ${$( (( $+commands[brew] )) && print -l "$(brew --prefix llvm)/bin" )}
  $HOME/{.local/bin,.bin,go/bin}
  /usr/local/{bin,sbin}
  /usr/local/opt/texinfo/bin
  $path
)


if [[ "$OSTYPE" == darwin* ]] ; then
  fpath=($(dirname ${ZPREZTODIR})/extra/macos-completions $fpath)
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
# Set TMPDIR if the variable is not set/empty or the directory doesn't exist
if [[ -z "${TMPDIR}" ]]; then
  export TMPDIR="/tmp/zsh-${UID}"
fi

if [[ ! -d "${TMPDIR}" ]]; then
  mkdir -m 700 "${TMPDIR}"
fi
