# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN || -z "${TMPDIR}" ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# pyenv-virtualenvwrapper
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--system-site-packages'
export WORKON_HOME="$HOME/.virtualenvs"
export VIRTUALENVWRAPPER_PYTHON="$HOME/.pyenv/shims/python"
export PROJECT_HOME="$HOME/Developer"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
