# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZPREZTODIR}/init.zsh" ]]; then
  source "${ZPREZTODIR}/init.zsh"
fi

# Customize to your needs...
alias apm='apm-beta'
alias atom='atom-beta'
alias numFiles='echo $(ls -1 | wc -l)'
alias oct='stat -f %Mp%Lp'
alias openPorts='lsof -Pan -i tcp -i udp'
alias sbb="subl ~/dotfiles/bash/"
alias l='logout'
alias szz="subl -n ~/dotfiles/prezto/runcoms"
alias rs="reset && exec $SHELL"
# Zshmarks
alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias p="showmarks"
alias eclim="/Applications/Eclipse.app/Contents/Eclipse/eclim"
alias eclimd="/Applications/Eclipse.app/Contents/Eclipse/eclimd"
alias ekill="ps aux | pgrep -i emacs | xargs kill"

autoload -U promptinit; promptinit
prompt pure



# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
