# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Jacob Chaffin <jchaffin@ucla.edu>
#

# Source Prezto.
if [[ -s "${ZPREZTODIR}/init.zsh" ]]; then
  source "${ZPREZTODIR}/init.zsh"
fi


# Command Not Found
# https://github.com/Homebrew/homebrew-command-not-found#install
if brew command command-not-found-init > /dev/null 2>&1; then
  eval "$(brew command-not-found-init)";
fi

# Zshmarks
alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias bl="showmarks"

if [[ "$OSTYPE" == darwin* ]] ; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
  export GOOGLE_APPLICATION_CREDENTIALS="$HOME/.gcloud/gcloud-commander-credentials.json"
fi

# Prepend user functions to fpath
fpath=($ZPREZTODIR/contrib/functions $fpath)

# Prompt
autoload -U promptinit; promptinit
prompt pure
