# -*- mode: sh; eval: (sh-set-shell "zsh") -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZPREZTODIR}/init.zsh" ]]; then
  source "${ZPREZTODIR}/init.zsh"
fi

# File Info
alias numFiles='echo $(ls -1 | wc -l)'
alias oct='stat -f %Mp%Lp'
# System
alias battery="pmset -g batt"
# Network
alias openPorts='lsof -Pan -i tcp -i udp'
alias establishedPorts='lsof -i | grep ESTABLISHED'
alias wifiOff='networksetup -setairportpower en0 off'
alias wifiOn='networksetup -setairportpower en0 on'
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'
# Session
alias rs="reset && exec $SHELL"
# User
alias sbb="subl ~/dotfiles/bash/"
alias szz="subl -n ~/dotfiles/prezto/runcoms"
alias eclim="/Applications/Eclipse.app/Contents/Eclipse/eclim"
alias eclimd="/Applications/Eclipse.app/Contents/Eclipse/eclimd"
alias ekill="ps aux | pgrep -i emacs | xargs kill"


# Zshmarks
alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias p="showmarks"

# Prompt
autoload -U promptinit; promptinit
prompt pure


# export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
